<p>Etes vous sûr de vouloir supprimer le message de
  '<?php echo $this->escape($this->message['email']); ?>' ?
    </p>
<form action="<?php echo $this->url(array('action'=>'deletemessage')); ?>" method="post">
<div>
  <input type="hidden" name="id" value="<?php echo $this->message['idmessage']; ?>" />
  <input type="submit" name="del" value="Yes" />
  <input type="submit" name="del" value="No" />
</div>
</form>