<div class="left">
    <h2>Le Site</h2>
    
    <ul>
        <li>Développer un site avec le Zend Framework 1</li>
        <li>Utiliser MYSQL -> pilote PDO</li>
        <li>Mettre à disposition le code source du site</li>
        <li>"désacraliser" l'utilisation du framework</li>
    </ul>

    <p>
        <a href="<?php echo $this->url(array('controller' => 'info', 'action' => 'structure')); ?>">Structure et composition du site</a>
    </p>

    <p>Si vous êtes intéressé par le <strong>ZEND FRAMEWORK 2</strong> -> c'est par <a href="../zf2">ici</a></p>
    <h2>Astuce !</h2>
    <p><img src="<?php echo $this->baseUrl(); ?>/public/images/info.png" border="0" title="Astuce !" alt="Astuce !"/>
    Chaque fois que vous recontrerez cet icône, il pointera vers une explication sur la mise en place de l'objet concerné.</p>
    <h2>Liste des messages</h2>
    <p>
        <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'newmessage')); ?>">Postez un message</a>
    </p>

    <table id="forumtab" width="" border="0">
        <?php foreach ($this->messages as $message) {
        ?>
            <tr>
            <?php
            echo "<td width='15%' valign='top'>";
            $date = new Zend_Date($message->created, Zend_Date::ISO_8601);
            $dt = $date->toString('d/M/Y');
            echo ucwords($dt);
            echo "</td>";
            echo "<td width='30%' valign='top'><b>";
            echo $this->escape($message->email);
            echo "</b></td>";
            echo "<td width='55%'>";
            echo stripslashes(nl2br($message->comment));
            echo "</td>";
            ?>
            <td width="5%"><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'editmessage', 'id' => $message->idmessage)); ?>">E</a></td>
            <td width="5%"><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'deletemessage', 'id' => $message->idmessage)); ?>">D</a></td>
        </tr>
        <?php
        }
        ?>
    </table>

    <p>&nbsp;</p>

</div>
<div class="left">
    <div id="boxright">
        <h1>MOTEUR DE RECHERCHE</h1>
        <?php
        echo $this->formmoteur;
        echo $this->moteur($this->query);
        ?>
        <p>
            <a href="<?php echo $this->url(array('controller' => 'info', 'action' => 'moteur')); ?>">
                <img src="<?php echo $this->baseUrl(); ?>/public/images/info.png" border="0" title="En savoir plus sur ce moteur..." alt="En savoir plus sur ce moteur..."/>
            </a>
        </p>
    </div>
    <p>&nbsp;</p>
    <div id="tag">
        <a href="<?php echo $this->url(array('controller' => 'tuto', 'action' => 'cloud')); ?>" alt="En savoir plus sur ce nuage de tag...">
            <img src="<?php echo $this->baseUrl(); ?>/public/images/info.png" border="0" alt="En savoir plus sur ce nuage de tag..." title="En savoir plus sur ce nuage de tag..." />
        </a>
        <?php
        $cloud = new Zend_Tag_Cloud(array(
                    'tags' => array(
                        array('title' => 'Navigation', 'weight' => 1,
                            'params' => array('url' => 'info/navigation')),
                        array('title' => 'ZEND_AUTH', 'weight' => 5,
                            'params' => array('url' => 'tuto/zfauth')),
                        array('title' => 'ZEND', 'weight' => 4,
                            'params' => array('url' => 'tuto/index')),
                        array('title' => 'Liens', 'weight' => 1,
                            'params' => array('url' => 'liens/index')),
                        array('title' => 'JQuery', 'weight' => 6,
                            'params' => array('url' => 'tuto/jquery')),
                        array('title' => 'Forums', 'weight' => 6,
                            'params' => array('url' => 'forum/index')),
                        array('title' => 'Tabcontainer', 'weight' => 2,
                            'params' => array('url' => 'tuto/tab')),
                        array('title' => 'Modules', 'weight' => 3,
                            'params' => array('url' => 'tuto/zfmodulaire')),
                        array('title' => 'Fil d\'ariane', 'weight' => 3,
                            'params' => array('url' => 'info/navig')),
                        array('title' => 'Xml', 'weight' => 4,
                            'params' => array('url' => 'tuto/xmletphp')),
                        array('title' => 'Zend_Navigation', 'weight' => 5,
                            'params' => array('url' => 'info/navig')),
                        array('title' => 'PhpInfo', 'weight' => 1,
                            'params' => array('url' => 'info/phpinfo')),
                        array('title' => 'accordion', 'weight' => 6,
                            'params' => array('url' => 'tuto/accordeon')),
                        array('title' => 'DatePicker', 'weight' => 3,
                            'params' => array('url' => 'tuto/datepicker')),
                        array('title' => 'sitemap', 'weight' => 3,
                            'params' => array('url' => 'info/sitemap')),
                        array('title' => 'MVC', 'weight' => 1,
                            'params' => array('url' => 'info/structure')),
                        array('title' => 'dialogue', 'weight' => 3,
                            'params' => array('url' => 'tuto/dialogue')),
                        array('title' => 'Message', 'weight' => 5,
                            'params' => array('url' => 'index/newmessage')),
                        array('title' => 'Zend_Paginator', 'weight' => 1,
                            'params' => array('url' => 'tuto/paginator')),
                    )
                ));


        echo $cloud;
        ?>

    </div>
    <p>

    </p>
</div>
<div class="clear"></div>