<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr">

    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
        <meta name="Author" content="Patricia LE STRAT" />
        <title>Patricia Le Strat :: Zend Framework 1</title>
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl(); ?>/public/css/header.css" />
        
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl(); ?>/public/css/content.css" />



    </head>

    <body>
        <div id="all">
            <div id="header">
                <img id="logozf" src="<?php echo $this->baseUrl(); ?>/public/images/zf.png" border="0" style="float:right"/>
                <h1>Patricia Le Strat :: Zend Framework 1</h1>
                <h2>ZF 1 en toute simplicité</h2>

            </div>




            <div id="content">

                <h1><?php echo $this->escape($this->title); ?></h1>
                <?php echo $this->layout()->content; ?>
            </div>

            <div id="footer">
                &copy; 2010 par <a href="../">Patricia LE STRAT</a> - Tous droits réservés


            </div>

        </div>
    </body>
</html>